```nix
{ config, pkgs, lib, ... }:

{
  imports = [
    ./hardware-configuration.nix
  ];

  # Basic system
  networking.hostName = "nixos";
  networking.networkmanager.enable = true;

  time.timeZone = "America/New_York";

  i18n.defaultLocale = "en_US.UTF-8";
  console.keyMap = "us";

  # Graphics
  hardware.graphics.enable = true;
  hardware.graphics.enable32Bit = true;

  # X11
  services.xserver = {
    enable = true;

    xkb = {
      layout = "us";
      variant = "";
    };

    # LightDM
    displayManager.lightdm = {
      enable = true;
      greeters.gtk.enable = true;
    };

    # dwm
    windowManager.dwm.enable = true;

    # Start desktop services with X11
    displayManager.sessionCommands = ''
      ${pkgs.picom}/bin/picom --daemon &
      ${pkgs.dunst}/bin/dunst &
    '';
  };

  # Make dwm the default session
  services.displayManager.defaultSession = "none+dwm";

  # Build dwm using our custom config.def.h
  nixpkgs.overlays = [
    (final: prev: {
      dwm = prev.dwm.overrideAttrs (oldAttrs: {
        postPatch =
          (oldAttrs.postPatch or "")
          + ''
            cp ${./dwm/config.def.h} config.def.h
          '';
      });
    })
  ];

  # Audio
  security.rtkit.enable = true;

  services.pipewire = {
    enable = true;

    alsa = {
      enable = true;
      support32Bit = true;
    };

    pulse.enable = true;
  };

  # Bluetooth
  hardware.bluetooth.enable = true;
  services.blueman.enable = true;

  # Flatpak
  services.flatpak.enable = true;

  # XDG Desktop Portal
  xdg.portal = {
    enable = true;

    extraPortals = [
      pkgs.xdg-desktop-portal-gtk
    ];

    config.common.default = "gtk";
  };

  # Steam
  nixpkgs.config.allowUnfree = true;
  programs.steam.enable = true;

  # Firefox
  programs.firefox.enable = true;

  # Existing NixOS user
  users.users.YOUR_USERNAME.extraGroups = [
    "wheel"
    "networkmanager"
    "audio"
    "video"
  ];

  # Fonts
  fonts.packages = with pkgs; [
    jetbrains-mono
    noto-fonts
    noto-fonts-emoji
  ];

  # Desktop applications and utilities
  environment.systemPackages = with pkgs; [
    # Terminal / launcher
    alacritty
    rofi

    # Desktop
    dunst
    picom
    thunar
    pavucontrol
    flameshot
    feh

    # dwm keybinding helpers
    i3lock
    wmctrl

    # System utilities
    fastfetch
    btop
    htop
    unzip
    zip
    p7zip
    wget
    curl
    git

    # Development
    gcc
    gnumake
    cmake
    pkg-config
    gdb

    # X11 development
    libX11
    libXft
    libXinerama
    xorgproto

    # X11 utilities
    xorg.xrandr
    xorg.xset
    xorg.xsetroot
    xorg.xev
    xorg.xprop
    xclip
  ];

  environment.variables = {
    EDITOR = "nano";
    VISUAL = "nano";
  };

  # Nix command / flakes support
  nix.settings.experimental-features = [
    "nix-command"
    "flakes"
  ];

  # Automatic garbage collection
  nix.gc = {
    automatic = true;
    dates = "weekly";
    options = "--delete-older-than 30d";
  };

  # Keep the version generated by your NixOS installer.
  system.stateVersion = "26.05";
}
```
